import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import { ToastContainer } from 'react-toastify';

import Header from '@/components/layout/Header';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';

// ----------------------------------------------------------------

const figtree = Figtree({ subsets: ['latin'], variable: '--font-figtree' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body className={`${figtree.variable} antialiased`}>
        <ToastContainer autoClose={20000} />
        <Header />
        <main className="mx-auto h-full min-h-screen">{children}</main>
      </body>
    </html>
  );
};

export default RootLayout;
